whitelist_rules:
  - colon
  - comma
  - empty_count
  - closing_brace
  - mark
  - trailing_semicolon
  - return_arrow_whitespace
  - redundant_nil_coalesing
  - private_unit_test
  - operator_whitespace
  - opening_brace
  - legacy_constructor
  - legacy_constant
  - legacy_cggeometry_functions
  - leading_whitespace
  - control_statement
  - mark
  - void_return
  - syntactic_sugar

excluded:
  - Carthage
  - Pods

colon:
  apply_to_dictionaries: false
